### ISSUE TITLE
Incorrect directory in installation instructions. 

### ISSUE THREAD

**Issue by tdeerenberg** [Lxtharia/minegrub-theme#1]
# The issue
The directory with the grub config file mentioned here is incorrect:
https://github.com/Lxtharia/minegrub-theme/blob/e267a9f42a07ce54968b5b8e20add550f9a7b915/README.md?plain=1#L8

You might have made a spelling mistake as the directory `/etc/defaults/` does not exist on the Linux filesystem by default and no applications will read from that directory. The directory that you are looking for is `/etc/default/` (and with the grub config file: `/etc/default/grub`).
<br><hr>

## Some explaination about `/etc/default`

Because you said in your notes [(on this line of README.md)](https://github.com/Lxtharia/minegrub-theme/blob/e267a9f42a07ce54968b5b8e20add550f9a7b915/README.md?plain=1#L22]) that you are not an expert concerning Linux, here is a brief explanation of what `/etc/default/` actually does:
>From [a post](https://www.linuxquestions.org/questions/slackware-14/the-directory-etc-default-723942/#post3531173) on a Slackware forum:
>
> >Basically, /etc/default contains some parameters that the end user or administrator is likely to change, rather than embedding the values in the actual boot scripts. In this way, changes will persist even if you upgrade the package and the boot script is replaced.
>
>In Debian, /etc/default/ is a directory of mostly empty files. The way it is meant to work is that each /etc/init.d/test script first sources /etc/default/test before starting/stopping the test service. The purpose of the file is to provide extra options for starting the service, or override certain aspects of the service's startup.

Source: [Ask Ubuntu: What is the purpose of /etc/default?](https://askubuntu.com/questions/429592/what-is-the-purpose-of-etc-default) 

Hope this helps!

**Comment by Lxtharia** [comment]
Thank you! Fixed the typo and thanks for the explanation! :D
