### ISSUE TITLE
License Problem 

### ISSUE THREAD

**Issue by efectn** [Lxtharia/minegrub-theme#2]
I couldn't see any license in root directory. Can you add a license? I would like to package this.

**Comment by Lxtharia** [comment]
Hello, i have to admit, i don't have an idea, what license i should add or what it should look like!

**Comment by RakuJa** [comment]
> Hello, i have to admit, i don't have an idea, what license i should add or what it should look like!

I suggest looking at https://tldrlegal.com/

**Comment by Lxtharia** [comment]
Thank you!
Added the MIT license, @efectn, thanks for packaging it!
