### ISSUE TITLE
Text goes out of button

### ISSUE THREAD

**Issue by rew1nter** [Lxtharia/minegrub-theme#20]
Is there any way to make this fit in the button or increase the button size?

**Comment by rew1nter** [comment]
![IMG_20230619_233228](https://github.com/Lxtharia/minegrub-theme/assets/64508791/595f894b-e69a-4d85-8e01-648d4f7c0372)

**Comment by johanno** [comment]
Hi I have a similar issue. My Buttons are over the package message in the bottom.

Is there a way to increase the resolution?

**Comment by Lxtharia** [comment]
If it's only grub that's in a low resolution, then you might need to add/change this line in your `/etc/default/grub` file:
```
...

# The resolution used on graphical terminal
# note that you can use only modes which your graphic card supports via VBE
# you can see them in real GRUB with the command `videoinfo'
GRUB_GFXMODE=1920x1080
...
```
Let me know if that solves it!

**Comment by johanno** [comment]
> If it's only grub that's in a low resolution, then you might need to add/change this line in your `/etc/default/grub` file:
> 
> ```
> ...
> 
> # The resolution used on graphical terminal
> # note that you can use only modes which your graphic card supports via VBE
> # you can see them in real GRUB with the command `videoinfo'
> GRUB_GFXMODE=1920x1080
> ...
> ```
> 
> Let me know if that solves it!
well after I forgot about this and now saw the notification i can confirm that 

`GRUB_GFXMODE=1920x1080` does not change anything. I first forgot to update grub, but after update-grub and a  reboot it stayed the same.

**Comment by Lxtharia** [comment]
Hm, does your screen have a really small resolution then? Would love to see an image!

The button sizes and the logo all have fixed size, so if the screen resolution is too small, everything gets crammed up.

**Comment by johanno** [comment]
No it is a 2k monitor but the 1k also shows the buttons too big. I can't see the bottom line at all

**Comment by Lxtharia** [comment]
Huh. I still don't really know how it looks, so I can only guess. 

Maybe try to use the recommended option that `videoinfo` outputs (when used in the grub console). If they change nothing, I'm currently out of ideas. 

Sidenote: It may be similar, but actually another problem than the original issue, so mightve been worth an own issue :)

**Comment by CatAhri** [comment]
In addition to making the buttons larger, I also abbreviated the text using `grub-customizer`.
