### ISSUE TITLE
Documentation: Install instructions for copying are faulty

### ISSUE THREAD

**Issue by Managor** [Lxtharia/minegrub-theme#22]
By default `/boot/grub/themes/minegrub-theme/` does not exist. Thus `sudo cp -ruv ./minegrub-theme/* /boot/grub/themes/minegrub-theme/` returns an error `cp: target '/boot/grub/themes/minegrub-theme/': No such file or directory`

**Comment by airpods69** [comment]
I was thinking of making a directory and doing that

**Comment by Lxtharia** [comment]
Thanks, fixed it in latest [commit](https://github.com/Lxtharia/minegrub-theme/commit/c52a1b6b2544523e72bd6dbac2972728324d6e67)

I don't know if there is a way to `cp` a folder recursively without the hidden `.git` folder, which would remove the need for that mkdir command.

**Comment by Managor** [comment]
A possibility would be to move the theme into its own directory in the repo.

**Comment by Lxtharia** [comment]
That's actually the perfect idea that my smooth brain didn't think of, thanks! I'll also clean up the other files a bit better, because right now the entire file tree is kind of a mess lmao
