### ISSUE TITLE
I wanted to complete the integration so I made this thing.

### ISSUE THREAD

**Issue by nikp123** [Lxtharia/minegrub-theme#28]
https://github.com/nikp123/minecraft-plymouth-theme

Currently it's missing files for mkinitcpio, but those can be added easily.

**Comment by Lxtharia** [comment]
Oh wow, that's awesome haha!!
(Tbh, i haven't heard of plymouth before, I kinda dig the text-only cryptic messages as my system magically stars)
But I kinda have to give this a try!

I also had secret plans to create a second grub theme in the style of the single player world selection menu. 
And having a main menu with a different grub.cfg (That will have the options "Singleplayer" and "Multiplayer") that will load the normally generated grub.cfg when selecting "Singleplayer". Even though this needs some grub config scripting or what, with this and your plymouth theme, it would be a seemless minecraft experience haha!

But loose plans aside, I'm happy I inspired you, it's great!

**Comment by nikp123** [comment]
Yeah, I just need to find time to polish this as it's quite rough around the edges at the moment.

**Comment by Lxtharia** [comment]
Closing this for now
