### ISSUE TITLE
hhhhhhhhhh,还吐槽我们，过分了

### ISSUE THREAD

**Issue by JasonZhuJunJie** [Lxtharia/minegrub-theme#37]
hhhhhhhhhh,还吐槽我们，过分了🤣🤣🤣🤣
![image](https://github.com/Lxtharia/minegrub-theme/assets/142644136/3d0849bc-5be2-4dc4-b688-52f3026d0b9a)

**Comment by 9Bakabaka** [comment]
What's wrong with you, this is the minegrub them repo, not bakabaka9/AZ-Minecraft-opener

**Comment by ltzXiaoYanMo** [comment]
主播你看看你发哪里了

**Comment by LxHTT** [comment]
iq boost :D

**Comment by LxHTT** [comment]
Don't disturb others' repo. It's bad manners.

**Comment by ltzXiaoYanMo** [comment]
lol

**Comment by olivertzeng** [comment]
> hhhhhhhhhh,还吐槽我们，过分了🤣🤣🤣🤣
> 
> ![image](https://github.com/Lxtharia/minegrub-theme/assets/142644136/3d0849bc-5be2-4dc4-b688-52f3026d0b9a)
> 
> 

不要來這邊亂啦

**Comment by LxHTT** [comment]
@Lxtharia just close or delete this issue plz

**Comment by olivertzeng** [comment]
> @Lxtharia just close or delete this issue plz

我不能關啊只有作者可以 @Lxtharia

**Comment by olivertzeng** [comment]
辛苦了 @LxHTT

**Comment by LxHTT** [comment]
> 辛苦了 @LxHTT

没什么的。主要是这个跑来添乱的

**Comment by KingofSpiders** [comment]
### **Please do not Issue anything unrelated to the project in this issue. Thank you for your cooperation.**

**Comment by olivertzeng** [comment]
> ### **Please do not Issue anything unrelated to the project in this issue. Thank you for your cooperation.**

# Bruh this issue is ALREADY unrelated to this project we are just telling the owner to shutdown this issue

**Comment by KingofSpiders** [comment]
> > ### **Please do not Issue anything unrelated to the project in this issue. Thank you for your cooperation.**
> 
> # Bruh this issue is ALREADY unrelated to this project we are just telling the owner to shutdown this issue

**## Yeah, of course that's what I'm saying**

**Comment by olivertzeng** [comment]
@LxHTT @KingofSpiders there are more trolls here https://github.com/Lxtharia/minegrub-theme/issues/18

**Comment by olivertzeng** [comment]
> > > ### **Please do not Issue anything unrelated to the project in this issue. Thank you for your cooperation.**
> 
> > 
> 
> > # Bruh this issue is ALREADY unrelated to this project we are just telling the owner to shutdown this issue
> 
> 
> 
> **Yeah, of course that's what I'm saying**

Oh okay

**Comment by 9Bakabaka** [comment]
我也不知道這位兄弟是怎麽吧這條issues發到這的

**Comment by olivertzeng** [comment]
> 我也不知道這位兄弟是怎麽吧這條issues發到這的

Bruh

**Comment by olivertzeng** [comment]
BTW 我不打 AZ 和高端 我打BNT

**Comment by KingofSpiders** [comment]
> 我也不知道這位兄弟是怎麽吧這條issues發到這的

估計是跟著你的上游倉庫找過來的。。。無語😓

**Comment by 9Bakabaka** [comment]
不至于不至于，我当初fork这个仓库是为了替换一下背景，结果闹出来这番事，属实是给开发者添麻烦了

**Comment by olivertzeng** [comment]
這裡除了我以外都是中國人嗎？我是台灣人

**Comment by LxHTT** [comment]
？

**Comment by 9Bakabaka** [comment]
是，我们都是来自中国大陆的人

**Comment by LxHTT** [comment]
台湾自古以来就是中国神圣不可分割的一部分

**Comment by olivertzeng** [comment]
好奇問而已

**Comment by LxHTT** [comment]
只是说你的说辞要准确点

**Comment by olivertzeng** [comment]
> 台湾自古以来就是中国神圣不可分割的一部分

我認為台灣不是中國的你認為是那就算了吧

我是沒差你要這麼認為乾我屁事

**Comment by olivertzeng** [comment]
> 只是说你的说辞要准确点

我沒有要要求你要說🇹🇼不是中國的但是你也不能強迫我說台灣是中國的

**Comment by olivertzeng** [comment]
等一下 @LxHTT 不要再討論了我們要討論的是要如何把這個下架

**Comment by KingofSpiders** [comment]
**Calm down, we don't want to have a dispute on a friendly exchange of code platform, so if there is a need for communication, it is recommended not to communicate on Github thanks**

**Comment by olivertzeng** [comment]
ok 👍🏼 @KingofSpiders

**Comment by olivertzeng** [comment]
> **Calm down, we don't want to have a dispute on a friendly exchange of code platform, so if there is a need for communication, it is recommended not to communicate on Github thanks**

The f ![image](https://github.com/Lxtharia/minegrub-theme/assets/86348833/52bbc0ac-1a99-4cd0-826a-fc64a978e80c)

**Comment by KingofSpiders** [comment]
> > **Calm down, we don't want to have a dispute on a friendly exchange of code platform, so if there is a need for communication, it is recommended not to communicate on Github thanks**
> 
> The f ![image](https://user-images.githubusercontent.com/86348833/268486649-52bbc0ac-1a99-4cd0-826a-fc64a978e80c.png)
It's just my opinion.

**Comment by KingofSpiders** [comment]
I think you can exchange your opinions on Telegram

**Comment by KingofSpiders** [comment]
Thats All

**Comment by olivertzeng** [comment]
> > > **Calm down, we don't want to have a dispute on a friendly exchange of code platform, so if there is a need for communication, it is recommended not to communicate on Github thanks**
> 
> > 
> 
> > The f ![image](https://user-images.githubusercontent.com/86348833/268486649-52bbc0ac-1a99-4cd0-826a-fc64a978e80c.png)
> 
> 
> 
> It's just my opinion.
> 
> 

I respect! We do what we think, we have different opinions that's fine.
We have a text in our textbook called [雅量](https://cgs.nkust.edu.tw/p/406-1078-14661,r634.php?Lang=zh-tw)

**Comment by olivertzeng** [comment]
> Thats All

BTW What can we do to shutdown/close this issue?

**Comment by KingofSpiders** [comment]
Therefore, my point of view is to contact AZ studio to cancel their ridiculous Issue, and then seek common ground while reserving differences or go to Telegram to explain and exchange my own views

**Comment by olivertzeng** [comment]
> So my point is to contact AZ studio to cancel their ridiculous Issue and then agree to disagree or go to Telegram to explain and exchange our views

That sounds like a great idea!

**Comment by olivertzeng** [comment]
> So my point is to contact AZ studio to cancel their ridiculous Issue and then agree to disagree or go to Telegram to explain and exchange our views

Followed! You're the most logical person in China, preceded only by the Belgium/Chinese YouTuber Ceylon Le Compte! I've followed your GitHub!

**Comment by KingofSpiders** [comment]
Please close the issue and move on

**Comment by olivertzeng** [comment]
> Please close the issue and move on
> 
> 

I can't do anything about it and I can't find the az something repo


BTW you said that telegram is a good platform. Let's chat there. ![image](https://github.com/Lxtharia/minegrub-theme/assets/86348833/11866bf9-efa1-4253-98bd-05d39cbdb1dc)

**Comment by JasonZhuJunJie** [comment]
我警告你Bakabaka_9，请尊重别人的软件，制作不易，请不要吐槽，这样非常不礼貌。还有，你貌似修改了我们的仓库，导致我们损失惨重，修复代码花费了1天时间，请问怎么处理。

**Comment by JasonZhuJunJie** [comment]
> 我也不知道這位兄弟是怎麽吧這條問題發到這的

Bakabaka_9，请尊重别人的软件，制作不易，请不要吐槽，这样非常不礼貌。还有，你貌似修改了我们的仓库，导致我们损失惨重，修复代码花费了1天时间，请问怎么处理。

**Comment by JasonZhuJunJie** [comment]
请你立即解决这个问题，谢谢

**Comment by JasonZhuJunJie** [comment]
作者同意你拉取分支了吗

**Comment by LxHTT** [comment]
GitHub是一个开源精神共享的地方，不是朱俊杰撒泼的地方。  
Fork是用来学习借鉴思考等用途的，不然要Fork功能何用  
还有，不要把自己的无能归咎于他人  
最后，不要打扰别人作者，在别人仓库发癫

**Comment by Lxtharia** [comment]
Sorry this is absolutely not related to anything here, I will lock this, please refrain from opening random unrelated issues on any platform like this to be honest, thanks
