### ISSUE TITLE
你们谁能把 Grub 的原版给我一份，谢谢

### ISSUE THREAD

**Issue by ZhuJunJie-Official** [Lxtharia/minegrub-theme#38]

**Comment by ltzXiaoYanMo** [comment]
主播又在拉屎了？

**Comment by Abjust** [comment]
真当github是你家厕所啊？

**Comment by ltzXiaoYanMo** [comment]
各位开发者抱歉耽误你们了，这个GitHub账号是[Issue37](https://github.com/Lxtharia/minegrub-theme/issues/37)发起者[JasonZhuJunjie](https://github.com/JasonZhuJunJie)的账号，记得标注下垃圾Issue，实在抱歉了

**Comment by Abjust** [comment]
pls close this issue, its spam again

**Comment by ltzXiaoYanMo** [comment]
Developers, I'm sorry for delaying you. This GitHub account is the account of [Jason Zhu Junjie](https://github.com/JasonZhuJunJie), the initiator of [Issue 37](https://github.com/Lxtharia/minegrub-theme/issues/37). Remember to mark the issue as spam. sorry

**Comment by Abjust** [comment]
sry for disturbing u again

**Comment by ltzXiaoYanMo** [comment]
iq boost 

:D

**Comment by Abjust** [comment]
> _No description provided._

这样打扰人家真的好吗？

**Comment by Lxtharia** [comment]
Please only submit issues in english and are related to this project
