### ISSUE TITLE
Update Service complaining about missing background

### ISSUE THREAD

**Issue by fkellner** [Lxtharia/minegrub-theme#39]
The `update-theme.py`-Script requires a folder `/boot/grub/themes/minegrub/backgrounds` to exist, but it does not after following instructions (even if you use the `choose-background.sh`-script, which is marked as optional). Pls add this folder or change the description :)

**Comment by fkellner** [comment]
Nevermind, I am stupid and cannot read

**Comment by Lxtharia** [comment]
Hello, yea, i couldn't figure out how to add an empty folder to git yet (or how to name the dummy file)
cause that missing folder annoyed me too lol
