### ISSUE TITLE
Text on MINEGRUB doesn't changed, after restart

### ISSUE THREAD

**Issue by VXEAD** [Lxtharia/minegrub-theme#44]
Hi that mean, that text "Im using arch btw" 
after im restarting my pc
I see that assets dir have file with this random text, but its still only "im using arch btw"
Btw i didn't see smth about this file, and i how to randomise this. Help me

**Comment by Lxtharia** [comment]
the update_theme.py script will manually pick a random line from that file and apply it. The trick is to run it automatically, either by copying the systemd service or by adding a command to [cron](https://wiki.archlinux.org/title/cron) 
with `sudo crontab -e`
and add something like `@reboot python /boot/grub/themes/minegrub/update_theme.py`
you can run that command manually (as root) too ofc, and see if something goes wrong

If the Readme is confusing, I would be very happy about feedback!

**Comment by VXEAD** [comment]
> the update_theme.py script will manually pick a random line from that file and apply it. The trick is to run it automatically, either by copying the systemd service or by adding a command to [cron](https://wiki.archlinux.org/title/cron) 
> with `sudo crontab -e`
> and add something like `@reboot python /boot/grub/themes/minegrub/update_theme.py`
> you can run that command manually (as root) too ofc, and see if something goes wrong
> 
> If the Readme is confusing, I would be very happy about feedback!
> 

Ok, thx. But if i use minegrub for Ventoy, this still not work. Like im just copy all files with pic, etc. I need install python script for it, or it cant don't work anymore?

**Comment by Lxtharia** [comment]
I don't know where the themes for ventoy are stored, but if they are on a removable drive, the python script needs to run the script in the directory of ventoys minegrub theme. So whatever distro you boot needs to run the script in that folder. Have you tried it manually?
