### ISSUE TITLE
Small font size

### ISSUE THREAD

**Issue by ChiefArug** [Lxtharia/minegrub-theme#45]
All text that isn't part of an image is very small.
![IMG20231201195657.jpg](https://github.com/Lxtharia/minegrub-theme/assets/73862885/59f8132d-5f5a-4e21-b5f9-5c3fd41dd426)
Screen Resolution is 1920x1080

I have tried using `grub-mkfont` to make a new .pf2 font file from the minecraft regular otf, but with the --size option set to bigger (tried 60 and 240), then putting that into the theme folder and changing the various mentions of `Minecraft Regular 30` to `Minecraft Regular 60` (or 240 for that) in theme.txt, but that didn't produce a noticeable effect.

I am using Grub Customizer to change the names of options, but this was a problem since before I started using that.

**Comment by felipetrentin** [comment]
Did anyone find a way to sign the fonts so that GRUB can load them without disabling secure boot?
