### ISSUE TITLE
resolution too low --- everything is too big so the bottom line is under the buttons

### ISSUE THREAD

**Issue by johanno** [Lxtharia/minegrub-theme#46]
The boot menu overlaps the timer and stuff.

I will update `videoinfo` when I get to it. But if I remember correctly it was 1920x1080.

**Comment by johanno** [comment]
![IMG_20231214_034753](https://github.com/Lxtharia/minegrub-theme/assets/3743347/c5e6568f-469f-421f-af72-879a2a66daf3)


![IMG_20231214_034446](https://github.com/Lxtharia/minegrub-theme/assets/3743347/013d656d-a6d8-4b47-abd1-85130829bbc6)

**Comment by Lxtharia** [comment]
Huh, it looks like your graphic card doesn't support any resolutions higher than 1024x768.

I also just learned that you can set fallback options in `GRUB_GFXMODE` like `GRUB_GFXMODE=2560x1440,1024x768,auto`. (https://wiki.archlinux.org/title/GRUB/Tips_and_tricks#Setting_the_framebuffer_resolution)

But nevertheless it will be stretched weirdly. I have to admit, that I don't really know what to do about it, sorry.
(Maybe a bios update or something can help? Don't try it unless you did some research on this haha)

Let me know if you can make any progress on this!

**Comment by johanno** [comment]
I'd rather not change a working Bios for a cool grub menu. I'll try the backup, but I probably will just leave it like that.

**Comment by johanno** [comment]
`GRUB_GFXMODE=2560x1440,1024x768,auto`

did the trick. nothing stretched. works fine

**Comment by Lxtharia** [comment]
Glad it worked out! :D
