### ISSUE TITLE
Can I use dynamic image format？

### ISSUE THREAD

**Issue by qwq2519** [Lxtharia/minegrub-theme#47]
I want the background to rotate, it will be very interesting

**Comment by Lxtharia** [comment]
Sadly, grub only supports .png files.
The only way I can think of to achieve this is maybe using the circular progress bar:

http://wiki.rosalab.ru/en/index.php/Grub2_theme_tutorial#circular_progress_-_Circular_indicator_of_elapsed_time
It will draw a set amount of "ticks" around a circle. (I don't know if they are rotated or not)
We have the option to use our background.png as the Tick image. 

If we then place this progress circle at the top left corner, make it 1px high and 500px wide, then make it use 1000 ticks, we can get it to "move" one pixel at a time.
It depends on the timeout though. That means if you have a 15s timeout, it will try to move back and forth in 15 seconds.
It will stop if you press any key.

MIght be worth to try out!

**Comment by Lxtharia** [comment]
Closing this, see #50
