### ISSUE TITLE
Incorrect Font Size

### ISSUE THREAD

**Issue by Jaso5** [Lxtharia/minegrub-theme#48]
The font size for the boot entries is too small.
The issue persists if I force a resolution (either native resolution or half size). I've tried tinkering with the fonts, but I was unable to fix it myself.
![PXL_20240121_153415382](https://github.com/Lxtharia/minegrub-theme/assets/62834013/e5b0d01d-8944-401b-a05c-10a0dc6999a5)

**Comment by Lxtharia** [comment]
Hi!

Look over at Issue #45 and reopen it if you still have problems! :>
