### ISSUE TITLE
Add an adaptive please

### ISSUE THREAD

**Issue by kostrominoff** [Lxtharia/minegrub-theme#5]
![изображение](https://user-images.githubusercontent.com/69917977/206864833-421f835b-b4f5-4af8-b6da-642053e28c28.png)

**Comment by Lxtharia** [comment]
Hello, as I wrote in the README, if you have more or less than 4 options, you can adjust the position of the bottom bar in the theme.txt:
change the `top = 40% + 314`  to `top = 40% + 386`, This should make it look clean again.

**Comment by kostrominoff** [comment]
Thanks!
