### ISSUE TITLE
Will the slogan under the logo be customizable in later version?

### ISSUE THREAD

**Issue by ichinose-chiya** [Lxtharia/minegrub-theme#51]
It seems that the slogan `"I use arch BTW"` is only a static pic now. If it could be customizable, that will be much more fantastic : )

**Comment by Lxtharia** [comment]
You can customize it!
Use the python script as described in the Readme: https://github.com/Lxtharia/minegrub-theme?tab=readme-ov-file#random-splash-texts-and-accurate-x-packages-installed-text
It will generate the static pic with the text you provide.
If you set up the systemd service, it will also switch to a random one every time you reboot!

**Comment by ichinose-chiya** [comment]
Thanks!
