### ISSUE TITLE
theme.txt

### ISSUE THREAD

**Issue by salehabdullah216** [Lxtharia/minegrub-theme#58]
I  got this error when I did sudo grub-mkconfig 

``/boot/grub/themes/minegrub/theme.txt: line 3: title-text:: command not found
/boot/grub/themes/minegrub/theme.txt: line 4: desktop-image:: command not found
/boot/grub/themes/minegrub/theme.txt: line 7: terminal-border:: command not found
/boot/grub/themes/minegrub/theme.txt: line 8: terminal-left:: command not found
/boot/grub/themes/minegrub/theme.txt: line 9: terminal-top:: command not found
/boot/grub/themes/minegrub/theme.txt: line 10: terminal-width:: command not found
/boot/grub/themes/minegrub/theme.txt: line 11: terminal-height:: command not found
/boot/grub/themes/minegrub/theme.txt: line 12: terminal-box:: command not found
/boot/grub/themes/minegrub/theme.txt: line 13: terminal-font:: command not found
/boot/grub/themes/minegrub/theme.txt: line 16: +: command not found
/boot/grub/themes/minegrub/theme.txt: line 21: left: command not found
top: unknown option '='
/boot/grub/themes/minegrub/theme.txt: line 23: width: command not found
/boot/grub/themes/minegrub/theme.txt: line 24: height: command not found
/boot/grub/themes/minegrub/theme.txt: line 26: item_font: command not found
/boot/grub/themes/minegrub/theme.txt: line 27: item_color: command not found
/boot/grub/themes/minegrub/theme.txt: line 28: selected_item_color: command not found
/boot/grub/themes/minegrub/theme.txt: line 29: item_height: command not found
/boot/grub/themes/minegrub/theme.txt: line 30: item_padding: command not found
/boot/grub/themes/minegrub/theme.txt: line 31: item_spacing: command not found
/boot/grub/themes/minegrub/theme.txt: line 32: scrollbar: command not found
/boot/grub/themes/minegrub/theme.txt: line 33: syntax error near unexpected token `}'
/boot/grub/themes/minegrub/theme.txt: line 33: `}'

**Comment by Lxtharia** [comment]
It looks like the theme.txt get's executed/interpreted by bash.

Which it should not.

How does your `/etc/default/grub` look like?
