### ISSUE TITLE
Sddm seems to not launch after installing. Undoing everything in installation doesn't fix it.

### ISSUE THREAD

**Issue by Jeremy5909** [Lxtharia/minegrub-theme#60]
```
Started Refresh existing PGP keys of archlinux-keyring regularly.
Started Daily man-d regeneration.
Started Daily verification of password and graup files.
Started Daily Cleanup of Temporary Directories.
Reached target Timer Units.
Listening on D-Bus System Message Bus Socket.
Listening on GnuPG network certificate management daemon for /etc/pacma I Listening on GnuPG cryptographic agent and passphrase cache (access for
Listening on GnuPG cryptographic agent and passphrase cache (restricted
Listening on GnuPG cryptographic agent (ssh-agent emulation) for /etc/p
Listening on GnuP cryptographic agent and passphrase cache for /etc/pa ] Listening on GnuPG public key management service for /etc/pacman.d/gnup
Listening on Hostname Service Socket.
Reached target Socket Units.
Starting D-Bus System Message Bus...
Started D-Bus System Message Bus.
Reached target Basic System.
Starting Network Manager...
Starting User Login Management...
Starting Hostname Service...
Started User Login Management.
Started Hostname Service.
Starting Network Manager Script Dispatcher Service...
Started Network Manager Script Dispatcher Service.
Started Network Manager.
Starting WPA supplicant...
Started WA supplicant.
Reached target Network.
Starting Permit User Sessions...
Finished Permit User Sessions.
Starting Hold until boot process finishes up...
Starting Terminate Plymouth Boot Screen...
```
Sorry for messups there, I extracted text from photo of my screen because I can't really do anything else. Using Arch linux, sddm, and KDE Plasma

When it was installed I just got the default boot menu aswell.

**Comment by Jeremy5909** [comment]
Kinda urgent as this is my main pc lol

**Comment by Lxtharia** [comment]
That certainly isn't good. So when booting you get to grub without the theme. And when booting it shows you the output you sent?
But you can login?
can you maybe post the history of the steps you took to install the theme?
Can you start SDDM via command line? Does it log anything?
the theme itself should not have broken much, its a bunch of files on the boot partition.
The most critical point is probably regenerating the grub.cfg.
Disclaimer: I have no real clue, just throwing some questions out there that may be helpful.

**Comment by Jeremy5909** [comment]
I get a black screen with my mouse (like theres no sddm) and switching to tty1 i tet that log and i can login through the other tyy's. `sudo systemctl start sddm` does nothing. I followed the installation instructions exactly and undoing it all doesnt fix it

**Comment by Jeremy5909** [comment]
I am using nvidia gpu with
`GRUB_CMDLINE_DEFAULT="loglevel=3 quiet nvidia_drm.modeset=1 nvidia_drm.fbdev=1 nvidia=NVreg_EnableGpuFirmware=0"` if that's important. It worked earlier with this and removing the nvidia stuff it still hangs on Terminate Plymouth Boot Screen.

**Comment by Jeremy5909** [comment]
Haha turns out had nothing to do with minegrub and was instead that Sweet wasn't compatible with KDE 6. My b
