### ISSUE TITLE
Example flake from readme build fail

### ISSUE THREAD

**Issue by Familex** [Lxtharia/minegrub-theme#66]
Code from readme does not build with an error:

```
minegrub-theme> Running phase: buildPhase
minegrub-theme> ERROR: The file background_options/1.8  - [Classic Minecraft] does not exist.
error: builder for '/nix/store/73dc06kry19343j3srsnh5mbfbpdjczj-minegrub-theme.drv' failed with exit code 1
```

I have tried pass in `minegrub-theme.background` `background_options/1.8 - [Classic Minecraft]` and `background_options/1.8 - [Classic Minecraft].png`, but that doesn't work either.

But `background_options/Alpha.png` works.

**Comment by rypervenche** [comment]
Use the version with ".png" at the end and note that with the 1.8 version there are 2 spaces after it. The minimal example is missing the ".png" at the end, but has the extra space that you're missing. @Familex

**Comment by Familex** [comment]
@rypervenche you're right, it's just the wrong path
