### ISSUE TITLE
"sudo grub-mkconfig -o /boot/grub/grub.cfg" outputs error 

### ISSUE THREAD

**Issue by tahayf** [Lxtharia/minegrub-theme#67]
Hello I'm new here! When I try to run this command it gives me this error:

```
Sourcing file `/etc/default/grub'
Sourcing file `/etc/default/grub.d/init-select.cfg'
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-6.8.0-40-generic
Found initrd image: /boot/initrd.img-6.8.0-40-generic
Found linux image: /boot/vmlinuz-6.5.0-18-generic
Found initrd image: /boot/initrd.img-6.5.0-18-generic
Memtest86+ needs a 16-bit boot, that is not available on EFI, exiting
Warning: os-prober will be executed to detect other bootable partitions.
Its output will be used to detect bootable binaries on them and create new boot entries.
Found Windows Boot Manager on /dev/nvme0n1p1@/EFI/Microsoft/Boot/bootmgfw.efi
Adding boot menu entry for UEFI Firmware Settings ...
done
```

I literally don't know anything about this Memtest86+ bro. What can I do to avoid that? What is the cause of this error? I guess because of that I can't update grub and I can't use Minegrub.

**Comment by Lxtharia** [comment]
Sorry bro, but i don't know. I'm pretty sure this is not a problem with the theme and it also doesn't seem that common.
You're probably better off asking on a forum or on reddit if you can't find a solution online.

Hope you'll find a fix for it so you can enjoy the theme :)

**Comment by tahayf** [comment]
thanks bro I'll find a way.
