### ISSUE TITLE
How to skip the popup thingy?

### ISSUE THREAD

**Issue by faizul726** [Lxtharia/minegrub-theme#69]
After i press any boot entry how do i skip the popup and directly go to boot?

**Comment by Lxtharia** [comment]
The pop up is the console which you can also open by pressing "C" while in the grub menu. When selecting an entry it apparently always opens the console (just in case it needs to print something like "Loading Linux...") so idk, I haven't found a way to hide it yet.

**Comment by PabloGomezBr** [comment]
And is there any way to use that console? Like to print a progress bar or something like that?

**Comment by Lxtharia** [comment]
if you look into your /boot/grub/grub.cfg, there are `menuentry`s that have been generated, printing out "Loading Linux". You could try to inject some echo commands there. 

See here: https://www.gnu.org/software/grub/manual/grub/html_node/Shell_002dlike-scripting.html

Let me know if you achieve a progress bar! Closing this for now.
