### ISSUE TITLE
Scaling to fit wider monitors

### ISSUE THREAD

**Issue by Oman395** [Lxtharia/minegrub-theme#7]
Hey, not sure if its possible, but it would be very nice to be able to scale this to wider monitors. Personally, I just made my own background, but it was a pain b/c I couldn't find the source image for the background and had to boot up beta 1.7.3 and take my own screenshot, and even now it doesn't really look perfect.

Alternatively, you could just take the image I made and put it in with the name background_wide.png, which would probably work just as well.
![Background](https://user-images.githubusercontent.com/77183348/207466621-75fb3e18-c305-4045-a807-d8580af83254.png)

**Comment by Lxtharia** [comment]
Hi! Your're right, there are currently only backgrounds for 1920x1080 (because i, too, made a screenshot of my minecraft home screen for that). I can try to place the logo seperately, so scaling backgrounds won't distort it, thanks for the feedback!

**Comment by Lxtharia** [comment]
Hi, background and logo are now seperated, so you should be able to replace the background more easily (or let it get stretched) #10 
I don't have a wide screen to test this on, so i'd love to hear feedback!
