### ISSUE TITLE
Set a random background on each boot up

### ISSUE THREAD

**Issue by MavikBow** [Lxtharia/minegrub-theme#71]
Should that be done via some sort of script that'd be launched after every boot, or are there any other options?

**Comment by Lxtharia** [comment]
Just like the splash text, randomizing the background is done by the update_theme script. It's a python script that is supposed to be run after every boot. Most distros can use the provided systemd service, but you can also do it with cron I think.
The script chooses a random background from all files located in `/boot/grub/themes/minegrub/backgrounds`. Files starting with an underscore are ignored.
Hope this answers the question? :)

**Comment by Samsu-F** [comment]
> Files starting with an underscore are ignored
Small correction: Not files starting with an underscore, but hidden files (i.e. starting with a dot) are ignored :)

**Comment by Lxtharia** [comment]
Ah, thanks!

No idea where I got the underscores idea from but i was too lazy too check 😄

**Comment by Samsu-F** [comment]
Ignoring files starting with an underscore was the first version (see commit 2a37a9d) but it was changed in commit 9a8b710.
I guess that's where you got it from :)

**Comment by Lxtharia** [comment]
Closing this
