### ISSUE TITLE
Settings buttons on each other 

### ISSUE THREAD

**Issue by depocoder** [Lxtharia/minegrub-theme#72]
![20241019_202546.jpg](https://github.com/user-attachments/assets/8850bbcb-d62f-4ccb-bf2e-725a63eee25b)

I use Manjaro, BTW :)

**Comment by depocoder** [comment]
I tried change GRUB_GFXMODE to "3440x1440x30,auto", haven't helped.

**Comment by depocoder** [comment]
@Lxtharia

**Comment by Lxtharia** [comment]
You need to edit the theme.txt file for that. The line and value you need to set it marked in there, you'll find it :)

https://github.com/Lxtharia/minegrub-theme?tab=readme-ov-file#adjusting-for-a-different-amount-of-boot-options

**Comment by Lxtharia** [comment]
@depocoder

**Comment by depocoder** [comment]
> @depocoder

Hi, saw your message, did not understand what actually I need to change. It seems to me that docs have not much info about it.

**Comment by Lxtharia** [comment]
in the cloned repository edit `./minegrub/theme.txt` and change [this line](https://github.com/Lxtharia/minegrub-theme/blob/f8c0b41dc585bc59921732befc7c3322c04f1a6a/minegrub/theme.txt#L71).
the copy the updated file to the boot partition:
`sudo cp -vu minegrub/theme.txt /boot/grub/themes/minegrub/theme.txt`

(you could also edit the file directly in place, i just take into account that when the theme gets updated you would copy the whole folder again, thus overriding the changed file)

Hope this is clear enough and you understand whats going on there. Please also tell me how to improve the README :>

**Comment by depocoder** [comment]
> in the cloned repository edit `./minegrub/theme.txt` and change [this line](https://github.com/Lxtharia/minegrub-theme/blob/f8c0b41dc585bc59921732befc7c3322c04f1a6a/minegrub/theme.txt#L71). the copy the updated file to the boot partition: `sudo cp -vu minegrub/theme.txt /boot/grub/themes/minegrub/theme.txt`
> 
> (you could also edit the file directly in place, i just take into account that when the theme gets updated you would copy the whole folder again, thus overriding the changed file)
> 
> Hope this is clear enough and you understand whats going on there. Please also tell me how to improve the README :>

Thanks a lot! That helped. 
Just add info how to fix this common issue like you wrote to me. Haven't found this info in readme.

**Comment by win10-ToZ-FreewheelinFrank** [comment]
man that glitch is just like my text editer when my things are UTF-8 INVIAD

**Comment by win10-ToZ-FreewheelinFrank** [comment]
speeking of glitchs i glitched this B\
