### ISSUE TITLE
Shadows for text 

### ISSUE THREAD

**Issue by OleSTEEP** [Lxtharia/minegrub-theme#9]
Hello, when I first saw this theme for GRUB, I was confused by the fact that the labels on the buttons look somehow wrong. I compared them with what I see in the game and realized what the problem is - the lack of shadows for the letters! It seems to me that adding shadows would have a positive effect on the visual part of this theme in the future. Perhaps you will find my [attempt](https://github.com/OleSTEEP/minegrub-modern-theme/commit/ea23a22cd443254a2525cf11168fb7b0362fc9b6) to add shadows to letters for this theme useful (There is a text alignment problem and in general I don’t quite like my implementation).

![preview_minegrub](https://user-images.githubusercontent.com/72727453/208243943-5e5ceb37-5743-4e71-bee6-fb64abb8a5d2.png)

**Comment by Lxtharia** [comment]
Looked through your theme.txt, does this actually work?? i didn't realize you could draw the boot menu items more than once. I haven't tested it yet, so i don't know what you mean with "text aligment problem". But thank you a lot! I will look into it, shadows would improve it a lot i think!

**Comment by OleSTEEP** [comment]
"Text alignment problem" (Text not in center):

![image](https://user-images.githubusercontent.com/72727453/208293192-d27f66b7-5efa-44f8-acb4-d27bd9a63dff.png)

**Comment by Lxtharia** [comment]
Ohh, i see.
The text always get placed in the middle of the field, so I will have to adjust the pixmaps a bit!

**Comment by Lxtharia** [comment]
Done! Thanks you, the whole theme looks a lot better now! :D
